"all":
  "hosts":
    "batuu-purple-proxmox.ca.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::be24:11ff:fe91:41d9"
      "ansible_port": 2222
      "ansible_user": "bine"
      "provider": "proxmox"
