---
- name: Configure ca.tjo.cloud
  hosts: all

  vars_files:
    - vars.yaml
    - vars.terraform.yaml

  handlers:
    - name: Restart step-ca
      ansible.builtin.systemd:
        name: step-ca
        state: restarted

  tasks:
    - name: Run defaults
      ansible.builtin.import_role:
        name: default
      vars:
        version: "{{ tjo_cloud_version }}"
        ssh_keys: "{{ tjo_cloud_admin_ssh_keys }}"
        configure_resolved: true

    - name: Install and Configure Observability
      ansible.builtin.import_tasks:
        file: tasks/observability.yaml

    - name: Install and Configure Firewall
      ansible.builtin.import_tasks:
        file: tasks/firewall.yaml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Configure ca
      ansible.builtin.include_tasks:
        file: tasks/ca.yaml
      tags:
        - step-ca-csr
        - config-reload

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags: config-reload
