"barman":
  "hosts":
    "barman.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.10"
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "18"
"postgresql":
  "hosts":
    "endor-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.12"
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "18"
    "nevaroo-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.11"
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "18"
