"barman":
  "hosts":
    "barman.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.10"
      "ansible_port": 2222
      "ansible_user": "bine"
"postgresql":
  "hosts":
    "pink-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.8"
      "ansible_port": 2222
      "ansible_user": "bine"
    "purple-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.9"
      "ansible_port": 2222
      "ansible_user": "bine"
