postgresql_version: "18" # this might be overded by cluster config in tfvars

restic_backup_dir: "/srv/data/barman"
restic_repository: "sftp://u409586-sub5@backup.tjo.cloud:23//home/backup"
#restic_password: ""
#restic_ssh_password: ""
