"barman":
  "hosts":
    "barman.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": ""
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "18"
"postgresql":
  "hosts":
    "endor-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.14"
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "16"
    "nevaroo-one.postgresql.tjo.cloud":
      "ansible_become": true
      "ansible_host": "10.0.4.13"
      "ansible_port": 2222
      "ansible_user": "bine"
      "postgresql_version": "16"
