- name: Install Notify Webhook
  ansible.builtin.import_role:
    name: notify-webhook

- name: Install Restic
  ansible.builtin.apt:
    name: restic
    state: present
    update_cache: yes

- name: Create /etc/restic
  ansible.builtin.file:
    state: directory
    path: "/etc/restic"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Template restic env file
  ansible.builtin.template:
    src: "../root/etc/restic/restic.env.j2"
    dest: "/etc/restic/restic.env"
    mode: '0600'
    owner: "root"
    group: "root"

- name: Write restic password
  ansible.builtin.copy:
    content: "{{ restic_password }}"
    dest: "/etc/restic/restic.password"
    mode: '0600'
    owner: "root"
    group: "root"

- name: Write restic repository
  ansible.builtin.copy:
    content: "{{ restic_repository }}"
    dest: "/etc/restic/restic.repository"
    mode: '0600'
    owner: "root"
    group: "root"

- name: Copy restic systemd files
  ansible.builtin.template:
    src: '../root/etc/systemd/system/{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
    mode: '0644'
    owner: "root"
    group: "root"
  loop:
    - restic-backup.service
    - restic-backup.timer
    - restic-check.service
    - restic-check.timer

- name: Create /usr/libexec/restic
  ansible.builtin.file:
    state: directory
    path: "/usr/libexec/restic"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Copy restic helpers
  ansible.builtin.template:
    src: '../root/{{ item }}'
    dest: '{{ item }}'
    mode: '0711'
    owner: "root"
    group: "root"
  loop:
    - /usr/libexec/restic/restic-backup
    - /usr/local/bin/restic-helper

- name: Check if restic was initialized
  ansible.builtin.command: |
    restic-helper cat config 2>/dev/null
  register: restic_init_check
  ignore_errors: true

- name: Restic Init
  ansible.builtin.command: |
    restic-helper init
  when: restic_init_check is failed
  run_once: true
  delegate_to: "{{ ansible_play_hosts[0] }}"

- name: Enable restic timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    daemon_reload: yes
  loop:
    - restic-backup.timer
    - restic-check.timer
