"all":
  "hosts":
    "batuu-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::be24:11ff:fe0f:5dcf"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "800G"
      "garage_zone": "batuu"
      "provider": "proxmox"
    "endor-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::be24:11ff:feda:8194"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "400G"
      "garage_zone": "endor"
      "provider": "proxmox"
    "jakku-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::be24:11ff:fe8b:50ff"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "800G"
      "garage_zone": "jakku"
      "provider": "proxmox"
    "mustafar-purple-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::be24:11ff:fe44:1c5b"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "400G"
      "garage_zone": "mustafar"
      "provider": "proxmox"
    "pink-hetzner-cloud.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::90ef:71ff:fe49:2599"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "gateway"
      "garage_size": "0G"
      "garage_zone": "germany"
      "provider": "hetzner-cloud"
