- name: Restart postgresql
  ansible.builtin.systemd:
    name: 'postgresql@{{ postgresql_version }}-main'
    state: restarted

- name: Reload postgresql
  ansible.builtin.systemd:
    name: 'postgresql@{{ postgresql_version }}-main'
    state: reloaded
