- name: Add repository
  ansible.builtin.deb822_repository:
    name: postgresql
    types: deb
    uris: https://apt.postgresql.org/pub/repos/apt
    suites: '{{ ansible_distribution_release }}-pgdg'
    components: main
    signed_by: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Install Postgresql
  ansible.builtin.apt:
    name: 'postgresql-{{ postgresql_version }}'
    state: present
    update_cache: true

- name: Install locales
  ansible.builtin.apt:
    name: locales-all
    state: present

- name: Install extensions
  ansible.builtin.apt:
    name: postgresql-{{ postgresql_version }}-{{ item }}
    state: present
  loop: "{{ postgresql_extensions }}"
