- name: Add repository
  ansible.builtin.deb822_repository:
    name: caddy
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    suites: any-version
    components: main
    signed_by: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: yes
